version: '3'

services:

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php
    container_name: 'micro-service-nginx'

  php:
    image: temafey/alpine-php:7.2-dev
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rmq
    container_name: 'micro-service-php'

  php-test:
    image: temafey/alpine-php:7.2-dev
    volumes:
      - .:/app
    container_name: 'micro-service-php-test'

  workers:
    image: temafey/alpine-php:7.2-dev
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rmq
    command: ['/app/bin/console', 'rabbitmq:multiple-consumer', 'events']
    container_name: 'micro-service-workers'

  mysql:
    image: percona:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql
    container_name: 'micro-service-mysql'

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: 'micro-service-rabbitmq'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - 5601:5601
    volumes:
      - "$PWD/etc/dev/kibana/config:/usr/share/kibana/config/kibana.yml"
    container_name: 'micro-service-kibana'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - "9200:9200"
    container_name: 'micro-service-elasticsearch'

volumes:
  db_data:
